version: '3.3'
services:
  db:
    container_name: invillia-recruitment-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'invillia_recruitment'
      MYSQL_USER: 'invillia'
      MYSQL_PASSWORD: 'invillia'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      
# Names our volume
volumes:
  my-db:            
  
